const mongoose=require("mongoose");
const courseSchema= new mongoose.Schema({
    courseName:{
        type:String,     
    },
    courseDescription:{
        type:String,
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        require:true,
        ref:"User",
    },
    courses:[
        {
           type:mongoose.Schema.Types.ObjectId,
           ref:"Course",
        }
    ],
    whatYouWillLearn:{
        type:String,
    },
    courseContent:[
        {
           type:mongoose.Schema.Types.ObjectId,
           ref:"Section",
        }
    ],
    ratingAndReview:[
        {
           type:mongoose.Schema.Types.ObjectId,
           ref:"RatingAndReview",
        }
    ],
    price:{
        type:Number,
    },
    thumbnail:{
        type:String,
    },
    studentsEnrolled:[{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"User"
    }],
});

module.exports=mongoose.model("Course",courseSchema);